### PR TITLE
✨ Introduce on click event on task

### PR DESCRIPTION
**Pull request by Lefevcal**
Hello, 
I have introduced a feature to listen on click event
I hope it fits in your project
Thanks

### CODE REVIEW

**Comment by MaTeMaTuK** [comment]
Hi @Lefevcal,
I really appreciate for you commit.
However, what is the difference between onClick and onSelect ?

**Comment by Lefevcal** [comment]
Hi @MaTeMaTuK 
With the onSelect the function is not triggered if the element is already selected
I need the simple click to trigger a function which hide children tasks of a project task 
And if the element is already selected and his children are hide, i need to select an other element to re click on the task to discover it children

**Comment by can-vaerks** [comment]
Please accept this, as we also need this for our project, and would like it to be implemented here instead of forking and implementing it ourselves :)

**Comment by MaTeMaTuK** [comment]
Ok. I will do this on this weekend with other changes.

**Pull request merged**
